version: "3.8"

services:
  # Base de Datos y Lógica (Node.js + SQLite)
  backend:
    build: ./backend
    container_name: gym-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite # Persistencia de los cobros
    environment:
      - NODE_ENV=production
    networks:
      - gym-network

  # Interfaz del Dueño (React + Vite)
  frontend:
    build: ./frontend
    container_name: gym-frontend
    ports:
      - "5173:5173" # Puerto por defecto de Vite
    depends_on:
      - backend
    networks:
      - gym-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Seguridad (Autenticación del Dueño)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: gym-auth
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - gym-network

networks:
  gym-network:
    driver: bridge
